services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER:     loanuser
      POSTGRES_PASSWORD: loanpass
      POSTGRES_DB:       loandb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loanuser -d loandb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: omarahorrar/loan-risk-backend:latest
    pull_policy: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://loanuser:loanpass@db:5432/loandb
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-net

  frontend:
    image: omarahorrar/loan-risk-frontend:latest
    pull_policy: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
    driver: bridge